server:
  port: 8080

spring:
  jackson:
    serialization:
#      removes errors in hibernate
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:postgresql://localhost:5432/client_interface
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true



